urls.py
from django.conf.urls.defaults import patterns, include, url
from open_fiddle import views


urlpatterns = patterns('',
    url(r'^$', views.FiddleEditorView.as_view(), name="new_fiddle"),
	url(r'^dashboard/$', views.DashboardView.as_view(), name="dashboard"),
	#~ url(r'^settings/$', views.UserSettingsView.as_view(), name="settings"),
	url(r'^upload/$', views.UploadView.as_view(), name="upload"),
   
    url(r'^iframe/(?P<pk>\d+)/$', views.FiddleIframeView.as_view(), name="fiddleframe"),
    url(r'^iframe/(?P<pk>\d+)/(?P<revision>\d+)/$', views.FiddleIframeView.as_view(), name="fiddleframe_revision"),
    
   
    url(r'^(?P<slug>[\w-]+)/$', views.FiddleEditorView.as_view(), name="edit_fiddle"),
    url(r'^(?P<slug>[\w-]+)/(?P<revision>\d+)/delete/$', views.FiddleDeleteView.as_view(), name="delete_fiddle"),
    url(r'^(?P<slug>[\w-]+)/(?P<revision>\d+)/$', views.FiddleEditorView.as_view(), name="edit_fiddle_revision"),
 
     url(r'^(?P<slug>[\w-]+)/embed/(?P<tabs>[a-zA-Z,]+)/$', views.FiddleEmbeddedView.as_view(), name="embed_fiddle"),
     url(r'^(?P<slug>[\w-]+)/(?P<revision>\d+)/embed/(?P<tabs>[a-zA-Z,]+)/$', views.FiddleEmbeddedView.as_view(), name="embed_fiddle_revision"),
   
    
    url(r'^ajax/(?P<mimetype>[\w-]+)/$', views.AjaxEchoView.as_view(), name="ajax_echo"),
    
)


models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from open_fiddle import wrapChoices, javascriptChoices, cssChoices
import json
import datetime
import os
import string
import random


		
	
class ActiveManager(models.Manager):
	def get_query_set(self):
		return super( ActiveManager, self ).get_query_set().filter( active=True )
		
class ActiveClass( models.Model ):
	active=models.BooleanField( default=True )
	objects=ActiveManager()
	allobjects=models.Manager()
	def activate(self):
		setattr( self, 'active', True )
		self.save()
	def deactivate(self):
		setattr( self, 'active', False )
		self.save()

	class Meta:
		abstract=True



class ResourceMixin( object ):
	def get_resources( self ):
		if not ( self.resources and self.resources.startswith( '[' ) ):
			return []
		return json.loads( self.resources )
		
class FrameworkGroup( models.Model ):
	name=models.CharField( max_length=100 )
	
	def __unicode__( self ):
		return self.name
		
class Framework( models.Model ):
	group=models.ForeignKey( FrameworkGroup )
	name=models.CharField( max_length=100 )
	version=models.CharField( max_length=20, null=True, blank=True )
	url=models.URLField()

	def __unicode__( self ):
		return self.name
		
class FrameworkDependent( ResourceMixin, models.Model ):
	''' available dependency for frameworks '''
	
	name=models.CharField( max_length=100 )
	version=models.CharField( max_length=20, null=True, blank=True )
	resources=models.TextField( blank=True )
	frameworks=models.ManyToManyField( Framework, help_text="Which frameworks support this dependency?", related_name="deps" )
	
	def __unicode__( self ):
		return self.name
		
class Resource( models.Model ):
	''' file either uploaded or added to be used inside a fiddle '''
	creator=models.ForeignKey( User )
	name=models.CharField( max_length=100, editable=False )
	url=models.URLField( blank=True )
	
	def save( self, *args, **kwargs ):
		self.name=os.path.basename( self.url )
		super( Resource, self ).save( *args, **kwargs )
		
	def __unicode__( self ):
		return self.name
		
class Fiddle( ResourceMixin, ActiveClass, models.Model ):
	framework=models.ForeignKey( Framework, blank=True, null=True  )
	wrap=models.CharField( choices=wrapChoices, max_length=20, default='domready' )
	slug=models.SlugField( editable=False )
	title=models.CharField( max_length=100, null=True, blank=True )
	revision=models.IntegerField( default=0, editable=False )
	temp=models.BooleanField( default=True, editable=False )
	base=models.BooleanField( default=False, editable=False )
	cssreset=models.BooleanField( default=True, blank=True )
	creator=models.ForeignKey( User, related_name="fiddles", editable=False, null=True )
	description=models.TextField( blank=True )
	created=models.DateTimeField( editable=False )
	revised=models.DateTimeField( editable=False )
	csspanel=models.CharField( choices=cssChoices, default='css', max_length=4 )
	jspanel=models.CharField( choices=javascriptChoices, default="javascript", max_length=15 )
	html=models.TextField( blank=True )
	css=models.TextField( blank=True )
	javascript=models.TextField( blank=True )
	resources=models.TextField( blank=True )
	framework_attrs=models.TextField( blank=True )
	bodytag=models.CharField( default='<body>', blank=True, max_length=150 )
	destroydate=models.DateTimeField( null=True )
	deps=models.ManyToManyField( FrameworkDependent )
	
	def save( self, *args, **kwargs ):
		self.revised=datetime.datetime.now()
		if not self.pk:
			self.created=datetime.datetime.now()
			if not self.slug:
				self.slug=generateSlug()
		super( Fiddle, self ).save( *args, **kwargs )
		

	def __unicode__( self ):
		return 'Fiddle #%d ~ %s ~ revision #%d %s' %( self.pk, self.slug, self.revision, 'TEMP' if self.temp else '' )

	def get_absolute_url( self ):
		''' absolute url for a fiddle is the editor '''
		if self.base:
			return reverse( 'edit_fiddle', kwargs={'slug': self.slug })
		return reverse( 'edit_fiddle_revision', kwargs={'slug': self.slug, 'revision': self.revision })

	def get_src_url( self ):
		if self.base:
			return reverse( 'fiddleframe', kwargs={'pk': self.pk })
		return reverse( 'fiddleframe_revision', kwargs={'pk': self.pk, 'revision': self.revision })

	def get_embedded_url( self, panels=[ 'html', 'results'] ):
		print 'get embedded url'
		panels=','.join( panels )
		if self.base:
			return reverse( 'embed_fiddle', kwargs={ 'slug': self.slug, 'tabs': panels })
		return reverse( 'embed_fiddle_revision', kwargs={ 'slug': self.slug, 'revision': self.revision, 'tabs': panels })
		
	def get_revisions( self ):
		''' get all revisions higher than and including this one '''
		return Fiddle.objects.filter( slug=self.slug, revision__gte=self.revision, temp=False ).order_by( 'revision' )
		
	#~ def getLatestRevision( self ):
		#~ queryset=Fiddle.objects.filter( creator=self.creator, slug=self.slug, temp=False ).order_by('-revision')
		#~ if queryset.count():
			#~ return queryset[ 0 ]
		#~ return self
		
		
	def get_js_resources( self ):
		resources=self.get_resources()
		return [ resource for resource in resources if resource.endswith('.js') ]
		
	def get_css_resources( self ):
		resources=self.get_resources()
		return [ resource for resource in resources if resource.endswith('.css') ]
		
		
def generateSlug( length=6, model=Fiddle ):
	slug=''.join( random.choice( string.letters ) for i in xrange( length ) )
	if ( model.objects.filter( slug=slug ).count() ):
		return generateSlug( length=length, model=model )
	return slug


	

templates/open_fiddle/base.html
{% extends 'open_fiddle/base_document.html' %}
{% block css %}
<link rel="stylesheet" href="{{ STATIC_URL }}reset.css" />
<link href='http://fonts.googleapis.com/css?family=Abel|Open+Sans+Condensed:300|Signika:400,600|Maven+Pro' rel='stylesheet' type='text/css'>
{% endblock %}






templates/open_fiddle/base_auth.html
{% extends 'base.html' %}
{% load cleverstyle_tags  %}
{% block body_class %}auth{% endblock %}


{% block css %}
	{{block.super}}
	{% cleverstyle 'auth.pcss' %}
{% endblock %}



templates/open_fiddle/dashboard.html
{% extends 'base.html' %}
{% load fiddle_tags cleverstyle_tags %}

{% block body_class %}dashboard{% endblock %}
{% block css %}
{{block.super}}
{% cleverstyle 'dashboard.pcss' %}
{% endblock %}

{% block javascript %}
{% include 'jquery.html' %}
<script src="{{STATIC_URL}}javascript/jquery-ui.min.js"></script>
<script src="{{STATIC_URL}}javascript/jquery.cookie.js"></script>
<script src="{{STATIC_URL}}javascript/jquery.form.js"></script>
<script src="{{STATIC_URL}}dashboard.js"></script>
{% endblock %}

{% block header %}
{{block.super}}
{% include 'open_fiddle/inc_inline_header_list.html' %}

{% endblock %}

{% block main %}
<div class="fiddleWrap">
	<div class="fiddleList">
		<div class="pagehead">
			<ul class="buttons right"><li><a href="/" class="right">New fiddle</a></li></ul>
		<h2>YOUR FIDDLE RIPOFFS</h2>
		</div>
		{% for fiddle in object_list %}
		<div class="fiddleDisplay">
			{% with fiddles=fiddle.get_revisions %}
			<ul class="revisionList">
				{% for f in fiddles %}
					<li{% if f.base %} class="base"{% endif %}>{% if f.base %}
						<a href="{{f.get_absolute_url}}">{{f.title}} <span class="slug">{{ f.slug }}</span></a>
					{% else %}
						<a href="{{f.get_absolute_url}}" class="fiddleName">revision #{{f.revision}}</a>
					{% endif %}
						
						<span class="date">{{f.created|date:"F j, Y h:i a"}}</span>
						<a href="{{f|embedded_url:"html,javascript,css,results"}}">Preview</a> [ <a class="delete" href="{% url 'delete_fiddle' f.slug f.revision %}" title="{% if f.base %}Delete this entire fiddle history{% else %}Delete this fiddle{% endif %}">x</a> ]
					</li>
				{% endfor %}
			</ul>
			{% endwith %}
		</div>
		{% empty %}
		<p class="emtpy">You have not saved any fiddles yet.</p>
		{% endfor %}
	</div>

	<form id="deleteForm" style="display: none;">
		{% csrf_token %}
	</form>
</div>
{% endblock %}

templates/open_fiddle/embedded.html
{% extends 'base.html' %}
{% load fiddle_tags %}

{% block body_class %}embedded{% endblock %}
{% block css %}
{{block.super}}
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/lib/codemirror.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/cobalt.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/eclipse.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/elegant.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/monokai.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/neat.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/night.css" />
<link rel="stylesheet" href="{{STATIC_URL}}javascript/codemirror/theme/rubyblue.css" />
{% endblock %}


{% block javascript %}
{% include 'jquery.html' %}
{% include 'backbone.html' %}
<script src="{{STATIC_URL}}javascript/keyboard.0.2.2.min.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/lib/codemirror.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/mode/javascript/javascript.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/mode/xml/xml.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/mode/css/css.js"></script>
<script src="{{STATIC_URL}}javascript/codemirror/mode/pcss/pcss.js"></script>
<script src="{{STATIC_URL}}models.js"></script>
<script src="{{STATIC_URL}}embedded.js"></script>
<script>
	var embedded=new $.EmbeddedFiddle({
		el: '#contentWrap',
		fiddle: {{object|json}}
	})
</script>
{% endblock %}

{% block header %}
{{block.super}}
<ul class="buttons right">
	<li class="group groupStart groupEnd"><a href="{{object.get_absolute_url}}" title="Edit this fiddle"><img src="{{STATIC_URL}}icons/edit.png" /></a></li>
</ul>
<ul class="buttons right tabbuttons">
	{% for tab in tabs %}
	<li class="group{% if forloop.first %} groupStart{% else %}{% if forloop.last %} groupEnd{% endif %}{% endif %}"><a href="#tab_{{tab.tab}}" class="tab{% if forloop.first %} selected{% endif %}">{{tab.name}}</a></li>
	{% endfor %}
</ul>
{% endblock %}

{% block main %}
<div id="contentWrap" class="embeddedWrap">
	{% for tab in tabs %}
	<div id="tab_{{tab.tab}}" data-name="{{tab.tab}}" class="tabContent" style="display: none">
		{% if tab.tab == 'results' %}
		<iframe src="{{object.get_src_url}}" id="resultFrame"></iframe>
		{% else %}
		<textarea name="{{tab.tab}}_ta">{{object|attrib:tab.tab}}</textarea>
		{% endif %}
	</div>
	{% endfor %}
</div>
{% endblock %}

templates/open_fiddle/fiddleform.html
{% extends 'open_fiddle/base.html' %}
{% load fiddle_tags  i18n %}

{% block body_class %}fiddle_edit {% if theme %}{{theme}}{% else %}default{% endif %}{% endblock %}

{% block css %}
{{block.super}}
{% include 'open_fiddle/inclusion/css.html' %}
{% endblock %}

{% block javascript %}
{{block.super}}
{% include 'open_fiddle/inclusion/javascript.html' %}
<script>
	$( function(){
		new $.Fiddle({
			el: '#fiddle'{% if object %},
			fiddle: {{object|json}}{% endif %}
		});
	});
</script>
{% endblock %}



{% block container %}
    <div id="header" class="header">
		<h1><a href="/">OPEN FIDDLE</a></h1>
	{% include 'open_fiddle/inclusion/site_links.html' %}
	{% include 'open_fiddle/inclusion/buttons.html' %}
	</div>

<div id="fiddle">
	<form method="post" action=" " id="fiddleForm">
		{% csrf_token %}
		{{form.resources}}
		<div id="fiddleWrap" class="wrapper">
			<div class="panel left leftPanel" id="sidebar">
				{% if object %}<p class="current_name" title="{% firstof object.title object.slug %}">{% firstof object.title object.slug %}</p>{% endif %}
				<ul class="accordion">
					<li><a href="#">{% trans 'Framework' %} (<span id="currentFramework" class="inlinespan">None</span>)</a>
						<div class="content">
							<p>{{form.wrap}}</p>
							<p>
								<select name="framework" id="id_framework">
									<option value="">None</option>
									{% for framework in frameworks %}
									{% ifchanged framework.group %}
									{% if not forloop.first %}</optgroup>{% endif %}
									<optgroup label="{{framework.group.name}}">{% endifchanged %}
									<option value="{{framework.pk}}">{{framework.name}}</option>
									{% endfor %}
								</select>
							</p>
							<div id="frameworkDeps" class="depslist">
							{{form.deps}}
							</div>
							<p>{{form.framework_attrs.label_tag}} {{form.framework_attrs}}</p>
							<p><label>{{form.cssreset}} Reset CSS</label></p>
						</div>
					</li>
					<li>
						<a href="#">{% trans 'Resources' %} (<span class="rsc" id="resourceCount">{{object.get_resources|length}}</span>)</a>
						<div class="content">
							<p class="combo">
								<a class="right button" href="#" id="resourceButton">+</a><input type="text" name="resource" /> 
								<a id="uploadResource" href="#">{% trans 'Upload' %}</a>
							</p>
							<ol id="resourceList">
								
							</ol>
							
						</div>
					</li>
					<li><a href="#">{% trans 'Panels' %}</a>
						<div class="content">
							<table class="panels">
								<thead></thead>
								<tbody>
									<tr>
										<td><select disabled="disabled"><option selected="selected">HTML</option></select></td>
										<td>{{form.csspanel}}</td>
									</tr>
									<tr>
										<td>{{form.jspanel}}</td>
										<td>Results</td>
									</tr>
								</tbody>
							</table>
						</div>
					</li>
					<li><a href="#">{% trans 'Info' %}</a>
						<div class="content">
							<p>{{form.title.label_tag}} {{form.title}}</p>
							<p>{{form.description.label_tag }} {{ form.description}}</p>
							<p>{{form.bodytag.label_tag}} {{form.bodytag}}</p>
					</div>
					</li>
				</ul>
			</div>
			
			<div class="panel rightPanel contentPanel" id="contentPanel">
				<div id="panelMask" class="panelMask"></div>
				<div class="panelWrap" id="resizeWrap">
				<a id="leftToggle" class="toggle" href="#" title="Hide Sidebar"></a>
					<div class="panelColumn" id="leftColumn">
						<div class="editor" id="HTMLEditor">{{form.html}}</div>
						<div class="resizer nsresizer"></div>
						<div class="editor" id="jsEditor">{{form.javascript}}</div>
					</div>
					<div class="resizer ewresizer"></div>
					<div class="panelColumn" id="rightColumn">
						<div class="editor" id="CSSEditor">{{form.css}}</div>
						<div class="resizer nsresizer"></div>
						<div class="editor" id="resultPanel"></div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<div id="overlay" class="overlay" style="display: none;"></div>
<div id="uploadModal" class="modal">
	<a class="close right" href="#"></a>
	<h3>UPLOAD</h3>
	<p>The accepted resource upload types are</p>
	<ul>
		<li><strong>{% trans 'Images' %}</strong> ( .png, .jpg, .gif )</li>
		<li><strong>{% trans 'Scripts' %}</strong> ( .js, .cs )</li>
		<li><strong>{% trans 'Stylesheets' %}</strong> ( .css, .scss, .pcss )</li>
	</ul>
	<p>{% trans "These files will be available to all your fiddles and can be added as resources and targeted inside your HTML ( if you're using the Django template setting)" %}</p>
	<form method="post" action="{% url 'upload' %}" enctype="multipart/form-data">
		{% csrf_token %}
		<p class="fileInput"><input type="file" name="resource" id="uploadInput" /></p>
	</form>
</div>
<div id="editorModal" class="modal editorModal">
	 <form method="get" action="">
		 <table>
			 <thead></thead>
			 <tbody>
				<tr>
					<th>Mode</th>
					<td class="mode"></td>
				</tr>
				<tr>
					<th>{{pform.theme.label_tag}}</th>
					<td>{{pform.theme}}</td>
				</tr>
				<tr>
					<th>{{pform.tabSize.label_tag}}</th>
					<td>{{pform.tabSize}}</td>
				</tr>
				<tr>
					<th>{{pform.lineWrapping.label_tag}}</th>
					<td>{{pform.lineWrapping}}</td>
				</tr>
				<tr>
					<th>{{pform.lineNumbers.label_tag}}</th>
					<td>{{pform.lineNumbers}}</td>
				</tr>
				<tr>
					<th>{{pform.firstLineNumber.label_tag}}</th>
					<td>{{pform.firstLineNumber}}</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>
<div id="optionsModal" class="modal optionsModal">
	<ul>
		<li><a href="#" id="exportFiddle" class="export">Export this fiddle</a></li>
		<li><a href="#" id="lintFiddle" class="export">JS Hint</a></li>
		<li><a href="#" id="tidyFiddle" class="export">JS Tidy</a></li>
		{% if object and object.creator == user %}<li><a href="#" id="deleteFiddle" class="remove">Delete this fiddle</a></li>{% endif %}
	</ul>
</div>
{% if object %}
<div id="exportModal" class="modal exportModal">
	<a class="close right" href="#" title="close"></a>
	<h3>EXPORT FIDDLE</h3>
	<form method="post" action="">
		{% csrf_token %}
		<table><thead></thead>
			<tbody>
				<tr>
					<th>{{exportform.name.label_tag }}</th>
					<td>{{exportform.name}}</th>
					<td class="help_text">{{exportform.name.help_text}}</td>
				</tr>
				<tr>
					<th>{{exportform.index_name.label_tag }}</th>
					<td>{{exportform.index_name}}</th>
					<td class="help_text">{{exportform.index_name.help_text}}</td>
				</tr>
				<tr>
					<th>{{exportform.format.label_tag }}</th>
					<td>{{exportform.format}}</th>
					<td class="help_text">{{exportform.format.help_text}}</td>
				</tr>
			</tbody>
		</table>
		<p class="center"><button type="submit">Export</button></p>
	</form>
</div>
{% endif %}
{% endblock %}

templates/open_fiddle/fiddleframe.html
{% load fiddle_tags %}
<!doctype html>
<html>
	<head>
		<meta http-Equiv="Cache-Control" Content="no-cache">
		<meta http-Equiv="Pragma" Content="no-cache">
		<meta http-Equiv="Expires" Content="0">	
		<title>{% firstof object.title "Fiddle Ripoff" %}</title>
		{% if object.cssreset %}
		<link rel="stylesheet" href="{{STATIC_URL}}reset.css" />
		{% endif %}
		{% for r in object.get_css_resources %}
		<link rel="stylesheet" href="{{r}}" />
		{% endfor %}
		{% if object.css %}
		<style>
			{% if object.csspanel == 'pcss' %}
			{{object.css|pcss}}
			{% else %}
				{% if object.csspanel == 'scss' %}
			{{object.css|scss}}
				{% else %}
			{{object.css|safe}}
				{% endif %}
			{% endif %}
		</style>
		{% endif %}
		{% if object.framework %}<script src="{{object.framework.url}}"{% if object.framework_attrs %} {{object.framework_attrs}}{% endif %}></script>{% endif %}
		{% if object.jspanel == 'coffeescript' %}
		<script src="{{STATIC_URL}}javascript/coffee-script.js"></script>
		{% endif %}
		
		{% if object.deps.count %}
		{% for dep in object.deps.all %}
		{% for url in dep.get_resources %}
		<script src="{{url}}"></script>
		{% endfor %}
		{% endfor %}
		{% endif %}
		{% for url in object.get_js_resources %}
		<script src="{{url}}"></script>
		{% endfor %}
		
		{% if object.wrap == 'head' %}{% include 'open_fiddle/inc_js.html' %}{% endif %}
	</head>
	{{object.bodytag|safe}}
		{{object.html|safe}}
		{% if object.wrap != 'head' %}{% include 'open_fiddle/inc_js.html' %}{% endif %}
	</body>
</html>

templates/open_fiddle/inc_coffee.html
<script type="text/coffeescript">
	{% if object.wrap == 'domready' %}
fn=() -> {{object.javascript|safe}}
		{% if object.framework.group.name == 'jQuery' %}
$( fn )
		{% else %}
fn()
		{% endif %}
	{% else %}
{{object.javascript|safe}}
	{% endif %}
	
</script>

templates/open_fiddle/inc_fiddle_list.html
<ul>
	{% for f in fiddles %}
	<li><a href="#">{{f.slug}} </a>
		{% if f.fiddle_set.count > 0 %}
		{% with fiddles=f.fiddle_set.all %}
		{# include 'fiddler/inc_fiddle_list.html' #}
		{% endwith %}
		{% endif %}
	</li>
	{% endfor %}
</ul>

templates/open_fiddle/inc_header_buttons.html
<ul class="buttons headerbuttons" id="fiddleButtons">
	<li class="groupEnd"><a href="#" id="runFiddle" title="Run this fiddle" class="run">Run</a></li>
	
	<li class="group groupStart"><a href="#" id="saveFiddle" title="{% if not object or object.temp %}Save a new copy{% else %}Update{% endif %}" class="save">{% if object %}Update{% else %}Save{% endif %}</a></li>
	
	<li class="group{% if not object %} groupEnd{% endif %}"><a href="#" id="resetFiddle" title="Reset all fields" class="reset">Reset</a></li>
	
	{% if object %}
	<li class="group groupEnd"><a href="#" id="forkFiddle" title="Create a clone of this fiddle" class="fork">Fork</a></li>
		{% if object.creator == user %}
			
	<li class="group groupStart groupEnd">
		{% if not object.base %}<a href="#" id="baseFiddle" title="Make this version the base" data-prop="baseFiddle" class="base">Base</a>
			{% else %}<span class="based" title="This is the base revision">Base</span></li>
			{% endif %}
		{% endif %}
	{% endif %}
	
	<li class="group groupStart groupEnd">
		<a href="#" id="optionsFiddle" class="options">Options</a>
	</li>
	
</ul>

templates/open_fiddle/inc_inline_header_list.html
<ul class="inline right">
	{% if user.is_authenticated %}
	<li><strong>Welcome {{user.username}}</strong></li>
	{% if user.is_staff %}<li><a href="/admin/">Admin</a></li>{% endif %}
	<li><a href="{% url 'dashboard' %}">Dashboard</a></li>
	<li><a href="{% url 'styleeditor' %}" target="_blank">Style Editor</a></li>
	<li><a href="{% url 'logout' %}">Logout</a></li>
	{% else %}
	<li><a href="{% url 'login' %}">Login</a></li>
	<li><a href="{% url 'register' %}">Register</a></li>
	{% endif %}
	
</ul>

templates/open_fiddle/inc_js.html
{% if object.jspanel == 'coffeescript' %}{% include 'open_fiddle/inc_coffee.html' %}{% else %}
<script >
	{% if object.wrap == 'domready' %}
		{% if object.framework.group.name == 'jQuery' %}
$( function(){
{{object.javascript|safe}}
});
		{% endif %}
	{% else %}
{{object.javascript|safe}}
	{% endif %}
</script>
{% endif %}

templates/open_fiddle/inc_theme_select.html
<select name="{{name}}_theme" class="theme_select">
	{% for url, name in manifest.themes %}
	<option value="{{name}}" {% if theme == name %}selected="selected"{% endif %}>{{name|capfirst}}</option>
	{% endfor %}
</select>

templates/open_fiddle/tmpl_editor_dropdown.html
<div class="dropdown ">
</div>